# permissions for end users to view k8stenantworkers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: karavy-workers
    app.kubernetes.io/managed-by: kustomize
  name: k8stenantworker-viewer-role
rules:
- apiGroups:
  - tenants.karavy.io
  resources:
  - k8stenantworkers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tenants.karavy.io
  resources:
  - k8stenantworkers/status
  verbs:
  - get
