---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: karavy-workers-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenants.karavy.io
  resources:
  - k8stenantworkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenants.karavy.io
  resources:
  - k8stenantworkers/finalizers
  verbs:
  - update
- apiGroups:
  - tenants.karavy.io
  resources:
  - k8stenantworkers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
