apiVersion: tenants.karavy.io/v1
kind: K8sTenant
metadata:
  labels:
    tenant-name: tenant-1
  name: tenant-1
  namespace: tenant-1
spec:
  kubeMasterDomain: cluster.local
  tenantApiServer:
    additionalArgs:
    - --v=10
    antiAffinity: true
    certificateDurationHours: 8760
    keycloak:
      enabled: false
    replicas: 1
  tenantControllerManager:
    antiAffinity: true
    certificateDurationHours: 8760
    replicas: 1
  tenantDNSServer:
    certificateDurationHours: 8760
  tenantEtcdServer:
    additionalArgs:
    - --initial-advertise-peer-urls=$(URI_SCHEME)://$(HOSTNAME).$(SERVICE_NAME).$(K8S_NAMESPACE):2380
    antiAffinity: true
    certificateDurationHours: 8760
    replicas: 3
    storageClassName: nfs-csi
    storageSize: 10Gi
  tenantNetwork:
    cniApplication:
      type: calico
      version: v3.29.2
    kubeDefaultSvc: 10.240.0.1
    podCidr: 16
    podNetwork: 10.120.0.0
    serviceCidr: 16
    serviceNetwork: 10.240.0.0
    tenantKubeDNSIP: 10.240.0.10
    tenantKubeDomain: tenant-1.local
  tenantScheduler:
    antiAffinity: true
    certificateDurationHours: 8760
    replicas: 1
  tenantVersions:
    tenantCrioVersion: v1.31.5
    tenantEtcdVersion: v3.5.18
    tenantKubeVersion: v1.31.5
  usersCertificates:
    certificateDurationHours: 8760
  winNodeSupport: true
  workerCertificates:
    certificateDurationHours: 8760
