---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: karavy-net-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - cilium.io
  resources:
  - ciliumnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - net.karavy.io
  resources:
  - karavyroutings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - net.karavy.io
  resources:
  - karavyroutings/finalizers
  verbs:
  - update
- apiGroups:
  - net.karavy.io
  resources:
  - karavyroutings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tenants.danielescattaglia.eu
  resources:
  - k8stenants
  - k8stenantworkers
  verbs:
  - get
  - list
  - watch
